apiVersion: v1
kind: Service
metadata:
  name: flask-stock-prediction-service
spec:
  selector:
    app: flask-stock-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  
