# -*- coding: utf-8 -*-
"""datagather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BU2qT0UDQWkQhOwBJsM3mNn8GJdbWb-S
"""

import requests
import pandas as pd

api_key = "3BPEMXGZ70LWNVX5"  # Your Alpha Vantage API key
symbol = "AAPL"  # Change this to the stock symbol you want (e.g., MSFT, TSLA)
function = "TIME_SERIES_DAILY"
outputsize = "compact"  # or "full" for more data

url = f"https://www.alphavantage.co/query"
params = {
    "function": function,
    "symbol": symbol,
    "outputsize": outputsize,
    "apikey": api_key
}

response = requests.get(url, params=params)
data = response.json()

if "Time Series (Daily)" in data:
    df = pd.DataFrame.from_dict(data["Time Series (Daily)"], orient="index")
    df = df.rename(columns=lambda x: x[3:])  # Rename '1. open' to 'open', etc.
    df.index.name = "Date"
    df = df.sort_index()

    # Save to CSV
    filename = f"{symbol}_daily.csv"
    df.to_csv(filename)
    print(f"✅ Data saved to {filename}")