name: Airflow + Flake8 + Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: windows-latest  

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U airflow"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Flake8
        run: |
          pip install flake8

      - name: Run Flake8 linting
        run: |
          flake8 . --max-line-length=79 --ignore=E203,W503  # You can customize the Flake8 options

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for Airflow and Database to be Ready
        run: |
          docker-compose exec -T airflow bash -c "airflow db init"
          docker-compose exec -T airflow bash -c "airflow users create -r Admin -u admin -p admin -e admin@example.com -f admin -l admin"
          docker-compose exec -T airflow bash -c "airflow webserver -D"
          docker-compose exec -T airflow bash -c "airflow scheduler -D"

      - name: Run tests
        run: |
          docker-compose exec -T airflow bash -c "pytest tests/test.py"

      - name: Shutdown Docker Compose
        run: docker-compose down
